apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: 540009924757.dkr.ecr.us-east-1.amazonaws.com/rag-generator:0.6  # Replace with your Docker image
        ports:
        - containerPort: 5000
