apiVersion: v1
kind: Service
metadata:
  name: chunk2vec-service #we forgot to change it here so currently its running as flask-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flask
